version: '3.8'

services:
  vonix-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vonix-network:latest
    container_name: vonix-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - .env
    volumes:
      # Persist database
      - ./data:/app/data
      # Persist logs
      - ./logs:/app/logs
      # Persist backups
      - ./backups:/app/backups
    networks:
      - vonix-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: vonix-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - vonix-backend
  #   networks:
  #     - vonix-network

networks:
  vonix-network:
    driver: bridge

volumes:
  data:
  logs:
  backups:
